# Note this is a sample file and should be modified to match your environment
testproj:
  outputs:
    dev:
      auth: CLI
      connect_retries: 0
      connect_timeout: 10
      endpoint: https://api.fabric.microsoft.com/v1
      lakehouse: lh_raw
      lakehouseid: a55e2f97-0df9-4e51-96b2-9876128713bd
      method: livy
      schema: dbo
      tenant_id: b403af0a-7f19-4079-ba08-1bcf4a56d79b
      threads: 5
      type: fabricsparknb
      workspaceid: 49cebc79-96d3-47cc-b610-7c58fcee5004
  target: dev
